### ISSUE TITLE
Geospatial 5.2.0-release does not work with DataNuclease release 5.2.10

### ISSUE THREAD

**Issue by siepkes** [datanucleus/datanucleus-geospatial#16]
Even though I would think changing the return type from `void` to `boolean` would be a backwards compatible change Java seems to take offense to it:

```
Caused by: java.lang.NoSuchMethodError: 'void org.datanucleus.store.types.geospatial.rdbms.adapter.PostGISAdapter.addSQLTypeForJDBCType(org.datanucleus.store.schema.StoreSchemaHandler, org.datanucleus.store.connection.ManagedConnection, short, org.datanucleus.store.rdbms.schema.SQLTypeInfo, boolean)'
	at org.datanucleus.store.types.geospatial.rdbms.adapter.PostGISAdapter.initialiseTypes(PostGISAdapter.java:67) ~[org.datanucleus.store.types.geospatial_5.2.0.release.jar:?]
	at org.datanucleus.store.rdbms.adapter.BaseDatastoreAdapter.initialise(BaseDatastoreAdapter.java:571) ~[org.datanucleus.store.rdbms_5.2.9.jar:?]
	at org.datanucleus.store.rdbms.RDBMSStoreManager.<init>(RDBMSStoreManager.java:301) ~[org.datanucleus.store.rdbms_5.2.9.jar:?]
	... 68 more
```

The return type was changed in this commit https://github.com/datanucleus/datanucleus-rdbms/commit/3fc4e94d251db407d09a76fecd7538bc194eb20b in datanucleus-rdbms. Which breaks Geospatial 5.2.0. I've verified this issue by rebuilding  datanucleus-geospatial using DN 5.2.10 as dependency. This fixes the issue.

**Comment by andyjefferson** [comment]
But I'm not reverting some change for no reason (which this is not). 
Perhaps you just want to rebuild datanucleus-geospatial against up to date datanucleus-rdbms, and then the conclusion is that datanucleus-geospatial just needs a re-release on 5.2.x

**Comment by andyjefferson** [comment]
Presumably works with 5.2.1 then.
